version: "3.9"
services:
  web:
    build: .
    ports:
      - "8787:8787"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  redis:
    image: "redis:7.2.5-bookworm"
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:12.19-bullseye"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env